server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5441/ead-authuser-db
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
